### PR TITLE
Create gettingStarted.md

### PR DESCRIPTION
**Pull request by pbuttigieg**
Changes for #379

### CODE REVIEW

**Comment by pbuttigieg** [comment]
@fils Was this the placeholder for the getting started guide? 

https://github.com/iodepo/odis-arch/blob/8bc09bdaf517f91eec6289f15438da67482c19df/book/_toc.yml#L15-L17

Are we defaulting to camelCase or snake-case?

**Comment by jmckenna** [comment]
> Are we defaulting to camelCase or snake-case?

camelCase is preferred (we should be consistent throughout all of our repos).

However this PR is confusing, as it there is a nicely formatted (and nicely named) gettingStarted.md (notice also the correct lowercase of the extension) in the root of the book directory.  Whereas this PR here has an oddly named directory and oddly named file, and leaves the other gettingStarted.md file as-is in the root.

Let's discuss this in the meeting Wednesday.

**Comment by jmckenna** [comment]
Answering my own comments here: I'll use this PR and update it, so it makes the changes into the existing `gettingStarted.md` file.

**Comment by jmckenna** [comment]
Aside: Let me know where to add these notes, for documentation rules in our repository:
- lines should not exceed 80 characters (some lines in this PR are around 1000 characters long, making it very difficult to read or edit)
- camelCase naming should be used for both files and directories
- `ODIS Federation` is the preferred way to discuss the ODIS network

**Review by fils — APPROVED** [review]

**Pull request merged**
