### PR TITLE
Fix lat,lon ordering and point separation in polygon examples

### PR DESCRIPTION
**Pull request by marksparkza**
Examples of `polygon` have been incorrectly formatted as `"lon lat"` pairs separated by commas. According to schema.org's definition of [GeoShape](https://schema.org/GeoShape), point pairs should be formatted either as `"lat lon"` or `"lat,lon"`, and points should be separated by whitespace, not commas.

### CODE REVIEW

**Comment by jmckenna** [comment]
@marksparkza thanks for the coordinate changes.  I wonder about your proposed no space after the comma, as I see other examples with a space after the comma.

**Comment by marksparkza** [comment]
I suspect that JSON-LD processors may be lenient in this regard - i.e. allow either space or no space after the comma. I am essentially following the schema.org recommendation of "Either whitespace or comma" as lat-lon separator. I opted for the comma because I think (my perception, ymmv) that it is easier to visually pick points out of a series if each lat-lon pair is joined with a comma.

**Comment by jmckenna** [comment]
@marksparkza I agree with your thoughts on this, and reasoning.  I am +1 for these changes.

**Comment by jmckenna** [comment]
@marksparkza thanks very much for your keen eye on this, it is very much appreciated.  Merging...

**Comment by jmckenna** [comment]
@marksparkza oh I just noticed (we recently changed to doing all updates into `master` branch).  Can you change this to `master` instead?

**Comment by marksparkza** [comment]
I've rebased onto master; closing this PR and will open a new one

**Pull request closed without merging**
